services:
  baseimage:
    image: func-az-kusto-base:latest
    hostname: func-az-kusto-base
    ports:
      - "7071:7071"
  rabbitmq:
    image: rabbitmq:3.11.9-management
    hostname: rabbitmq
    ports:
      - "7000:15672"
      - "7001:5672"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
